### PR TITLE
Replace node-fetch with undici (closes #2)

### LINKED ISSUE #2: FetchError: maximum redirect reached
Hello.

Recently all our calls via this lib are failing with `FetchError: maximum redirect reached`

Example failing code:

```js
import ChromeWebStore from 'webextension-store-meta/lib/chrome-web-store/index.js'

await ChromeWebStore.load({ id: 'iocghaljaochhkgajdilelogdkejkiil' })
```

### PR DESCRIPTION
**Pull request by xmcp**
`undici` seems to support redirecting with a non-ASCII `Location` response header from Chrome Web Store

### CODE REVIEW

**Comment by crimx** [comment]
Thanks for the PR! It seems there's a linting issue. Could you also provide a test that covers the fix?

**Comment by xmcp** [comment]
Fixed the linting issue.

Any extension with a non-ASCII name can serve as a test. E.g., https://chromewebstore.google.com/detail/%E5%96%B5%E5%96%B5%E6%8A%98+/ekbmhggedfdlajiikminikhcjffbleac?hl=en

**Comment by xmcp** [comment]
Oops, it seems that undici [claims to support only Node 18+](https://github.com/nodejs/undici/blob/main/package.json#L128), and it is using nullish coalescing assignment (`??=`) that [only works for Node 15+](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_assignment#browser_compatibility) so the test fails on Node 14.

Since major downstream projects are all using Node 18+ (20 for [shields.io](https://github.com/badges/shields/blob/master/package.json#L216) and 18 for [badgen](https://github.com/badgen/badgen.net/blob/main/package.json#L68)), is it safe to just raise the Node version requirement to 18?

**Comment by crimx** [comment]
Updated🎉

**Comment by xmcp** [comment]
Thanks! Can you bump the version number and release to npm, so that I can ask shields.io for an update?

**Comment by crimx** [comment]
Sure I am adding TypeScript. Almost done.

**Comment by crimx** [comment]
`webextension-store-meta@1.2.0`

**Pull request merged**
